language: cpp
os: windows
script:
  - git clone --branch v3.1.2 https://github.com/wxWidgets/wxWidgets.git lib/wxWidgets
  - cd lib/wxWidgets/build/msw ; mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release setup_h
  - cd lib/wxWidgets/build/msw ; mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release -j 8
  - mingw32-make
