language: cpp
os: windows
script:
  - choco install wxwidgets
  - junction lib/wxWidgets  C:/wxWidgets-3.1.2
  - cd lib/wxWidgets/build/msw ; mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release setup_h
  - cd lib/wxWidgets/build/msw ; mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release -j 8
  - mingw32-make
