language: cpp
os: windows
script:
  - choco install wxwidgets
  - cd C:/wxWidgets-3.1.2/build/msw ; mingw32-make -f makefile.gcc -j 8 SHARED=0 UNICODE=1 BUILD=release
  - junction lib\wxWidgets-3.1.2  d:\project\misc\wxWidgets-3.1.2
  - mingw32-make
