language: cpp
os: windows
script:
  - choco install wxWidgets --version 3.1.2
  - pushd C:/wxWidgets-3.1.2/build/msw ; mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release setup_h; popd
  - pushd C:/wxWidgets-3.1.2/build/msw ; mingw32-make -f makefile.gcc SHARED=0 UNICODE=1 BUILD=release -j 8; popd
  - mingw32-make WXWIDGETS_DIR=C:/wxWidgets-3.1.2 -j 8
  - 7z a -tzip rel/BletchMAME.zip ./bin/mingw_win64/release/BletchMAME.exe

cache:
  directories:
  - C:/wxWidgets-3.1.2/build/msw/gcc_mswu
  
deploy:
  provider: s3
  bucket: bletchmame
  skip_cleanup: true
  local_dir: rel
  upload-dir: files
